############################################################################################
# Market YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# NOTE: XBT is the same currency code as BTC for Bitcoin on itBit exchange.
############################################################################################
---
markets:

  # The id value is the market id as defined on the exchange, e.g. 'XBTUSD'.
  - id: XBTUSD

    # A friendly name for the market.
    # Value must be an alphanumeric string. Spaces are allowed. E.g. XBT/USD
    name: XBT/USD

    # The baseCurrency value is the currency short code for the base currency in the currency pair. When you buy or sell a
    # currency pair, you are performing that action on the base currency. The base currency is the commodity you are buying or
    # selling. E.g. in a XBT/USD market, the first currency (XBT) is the base currency and the second currency (USD) is the
    # counter currency.
    baseCurrency: XBT

    # The counterCurrency value is the currency short code for the counter currency in the currency pair. This is also known
    # as the quote currency.
    counterCurrency: USD

    # The enabled value allows you toggle trading on the market - config changes are only applied on startup.
    enabled: true

    # The tradingStrategyId value must match a strategy id defined in your strategies.yaml config.
    # Currently, BX-bot only supports 1 strategy per market.
    tradingStrategyId: scalping-strategy

