############################################################################################
# Market YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# NOTE: XXBT is the same currency code as BTC for Bitcoin on Kraken exchange.
############################################################################################
---
markets:

  # The id value is the market id as defined on the exchange, e.g. 'XBTUSD'.
  # Kraken markets assets (e.g. currencies) can be referenced using their ISO4217-A3 names in the case of ISO
  # registered names, their 3 letter commonly used names in the case of unregistered names,
  # or their X-ISO4217-A3 code (see http://www.ifex-project.org/).
  #
  # The Kraken Exchange Adapter expects the market id to use the 3 letter commonly used names,
  # e.g. you access the XBT/USD market using 'XBTUSD'. The reason for this is because the Kraken OpenOrders API
  # call returns orders with asset pair id to identify the market - this is in the 3 letter commonly used name
  # format, and the adapter uses the marketId to filter the returned orders.
  - id: XBTUSD

    # A friendly name for the market.
    # Value must be an alphanumeric string. Spaces are allowed. E.g. XBT/USD
    name: XBT/USD

    # The baseCurrency value is the currency short code for the base currency in the currency pair. When you buy or sell a
    # currency pair, you are performing that action on the base currency. The base currency is the commodity you are buying or
    # selling. E.g. in a XBT/USD market, the first currency (XBT) is the base currency and the second currency (USD) is the
    # counter currency.
    #
    # Markets assets (currencies) can be referenced using their ISO4217-A3 names in the case of ISO registered names,
    # their 3 letter commonly used names in the case of unregistered names,
    # or their X-ISO4217-A3 code (see http://www.ifex-project.org/).
    #
    # The Kraken Exchange Balance API call always returns the currency short code in the X-ISO4217-A3 format, so you must
    # specify your codes the same way here. E.g. XBT must be specified as 'XXBT'.
    baseCurrency: XXBT

    # The counterCurrency value is the currency short code for the counter currency in the currency pair. This is also known
    # as the quote currency.
    #
    # Markets assets (currencies) can be referenced using their ISO4217-A3 names in the case of ISO registered names,
    # their 3 letter commonly used names in the case of unregistered names,
    # or their X-ISO4217-A3 code (see http://www.ifex-project.org/).
    #
    # The Kraken Exchange Balance API call always returns the currency short code in the X-ISO4217-A3 format, so you must
    # specify your codes the same way here. E.g. USD should be specified as 'ZUSD'.
    counterCurrency: ZUSD

    # The enabled value allows you toggle trading on the market - config changes are only applied on startup.
    enabled: true

    # The tradingStrategyId value must match a strategy id defined in your strategies.yaml config.
    # Currently, BX-bot only supports 1 strategy per market.
    tradingStrategyId: scalping-strategy
