############################################################################################
# Exchange Adapter YAML config.
#
# - Sample config below currently set to run against Gemini.
# - All fields are mandatory unless stated otherwise.
# - BX-bot only supports running 1 exchange per bot.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# See the README "How do I write my own Exchange Adapter?" section for more details.
############################################################################################
---
exchange:

  # A friendly name for the Exchange. Value must be an alphanumeric string. Spaces are allowed.
  name>: Gemini

  # For the adapter value, you must specify the fully qualified name of your Exchange Adapter class so the Trading Engine
  # can load and execute it. The class must be on the runtime classpath.
  adapter: com.gazbert.crypto.exchanges.GeminiExchangeAdapter

  authenticationConfig:
    # Add your Gemini Trading API credentials as per instructions here: https://exchange.gemini.com/settings/api
    key: your-api-key
    secret: your-secret-key

  networkConfig:
    # This value is in SECONDS. It is the timeout value that the exchange adapter will wait on socket connect/socket read
    # when communicating with the exchange. Once this threshold has been breached, the exchange adapter will give up and
    # throw a Trading API TimeoutException.
    #
    # The exchange adapter is single threaded: if one request gets blocked, it will block all subsequent requests from
    # getting to the exchange. This timeout prevents an indefinite block.
    #
    # You'll need to experiment with values here.
    connectionTimeout: 30

    # Optional HTTP status codes that will trigger the adapter to throw a non-fatal ExchangeNetworkException
    # if the exchange returns any of the below in an API call response:
    nonFatalErrorCodes: [502, 503, 504, 520, 522, 525]

    # Optional java.io exception messages that will trigger the adapter to throw a non-fatal ExchangeNetworkException
    # if the exchange returns any of the below in an API call response:
    nonFatalErrorMessages:
      - Connection reset
      - Connection refused
      - Remote host closed connection during handshake
      - Unexpected end of file from server

  otherConfig:
    # Exchange Taker Buy fee in %
    # IMPORTANT - keep an eye on the fees: https://gemini.com/fee-schedule/
    # Taker fee on 3 Aug 2016 = 0.25%
    buy-fee: 0.25

    # Exchange Taker Sell fee in %
    # IMPORTANT - keep an eye on the fees: https://gemini.com/fee-schedule/
    # Taker fee on 3 Aug 2016 = 0.25%
    sell-fee: 0.25
